import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../models/payment_model.dart';
import '../../../services/payment_assistant_service.dart';
import '../../../providers/payment_provider.dart';

class PaymentAssistantDialog extends ConsumerStatefulWidget {
  const PaymentAssistantDialog({super.key});

  @override
  ConsumerState<PaymentAssistantDialog> createState() =>
      _PaymentAssistantDialogState();
}

class _PaymentAssistantDialogState
    extends ConsumerState<PaymentAssistantDialog> {
  final _controller = TextEditingController();
  bool _isLoading = false;
  Map<String, dynamic>? _extractedData;
  String? _error;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _processPrompt() async {
    if (_controller.text.trim().isEmpty) return;

    setState(() {
      _isLoading = true;
      _error = null;
      _extractedData = null;
    });

    try {
      final assistant = ref.read(paymentAssistantServiceProvider);
      final data = await assistant.processPaymentPrompt(
        _controller.text.trim(),
      );
      setState(() {
        _extractedData = data;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  Future<void> _confirmAndRecord() async {
    if (_extractedData == null) return;

    setState(() => _isLoading = true);

    try {
      final repo = ref.read(paymentRepositoryProvider);

      final payment = Payment(
        id: '', // Will be generated by Firestore
        partyId: _extractedData!['partyId'],
        partyName: _extractedData!['partyName'],
        paymentType: _extractedData!['paymentType'],
        paymentDate: DateTime.parse(_extractedData!['paymentDate']),
        totalAmount: _extractedData!['totalAmount'],
        paymentMethod: _extractedData!['paymentMethod'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final List<PaymentAllocation> allocations =
          (_extractedData!['allocations'] as List)
              .map(
                (a) => PaymentAllocation(
                  invoiceId: a['invoiceId'],
                  invoiceNumber: a['invoiceNumber'],
                  allocatedAmount: (a['allocatedAmount'] as num).toDouble(),
                ),
              )
              .toList();

      await repo.recordPayment(payment, allocations);

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              'Payment recorded for ${_extractedData!['partyName']}',
            ),
          ),
        );
      }
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final fmt = NumberFormat.currency(locale: 'en_IN', symbol: '₹');

    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
        left: 20,
        right: 20,
        top: 20,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              const Icon(Icons.auto_awesome, color: Colors.blue),
              const SizedBox(width: 12),
              Text(
                'AI Payment Assistant',
                style: Theme.of(
                  context,
                ).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold),
              ),
              const Spacer(),
              IconButton(
                onPressed: () => Navigator.pop(context),
                icon: const Icon(Icons.close),
              ),
            ],
          ),
          const SizedBox(height: 8),
          const Text(
            'Tell me about a payment you received or made. For example: "I received ₹5,000 from ABC Enterprises via UPI today"',
            style: TextStyle(color: Colors.grey, fontSize: 13),
          ),
          const SizedBox(height: 20),

          if (_extractedData == null) ...[
            TextField(
              controller: _controller,
              decoration: InputDecoration(
                hintText: 'Enter payment details...',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                suffixIcon: IconButton(
                  onPressed: _isLoading ? null : _processPrompt,
                  icon: const Icon(Icons.send),
                ),
              ),
              maxLines: 2,
              enabled: !_isLoading,
            ),
          ] else ...[
            _buildResultCard(context, fmt),
          ],

          if (_error != null) ...[
            const SizedBox(height: 12),
            Text(
              _error!,
              style: const TextStyle(color: Colors.red, fontSize: 12),
            ),
          ],

          const SizedBox(height: 20),
          if (_isLoading)
            const Center(
              child: Padding(
                padding: EdgeInsets.all(20.0),
                child: CircularProgressIndicator(),
              ),
            )
          else if (_extractedData != null)
            ElevatedButton(
              onPressed: _confirmAndRecord,
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Text('Confirm and Record Payment'),
            )
          else
            ElevatedButton(
              onPressed: _processPrompt,
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Text('Analyze with AI'),
            ),
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  Widget _buildResultCard(BuildContext context, NumberFormat fmt) {
    final data = _extractedData!;
    final allocations = data['allocations'] as List;

    return Card(
      elevation: 0,
      color: Colors.blue.shade50,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(color: Colors.blue.shade200),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  data['partyName'],
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
                Text(
                  fmt.format(data['totalAmount']),
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.blue,
                    fontSize: 16,
                  ),
                ),
              ],
            ),
            const Divider(),
            Text(
              'Type: ${data['paymentType'] == 'receipt' ? 'Receipt (In)' : 'Payment (Out)'}',
            ),
            Text('Method: ${data['paymentMethod'].toString().toUpperCase()}'),
            const SizedBox(height: 12),
            const Text(
              'Allocations (FIFO):',
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
            ),
            ...allocations.map(
              (a) => Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      'Inv #${a['invoiceNumber']}',
                      style: const TextStyle(fontSize: 12),
                    ),
                    Text(
                      fmt.format(a['allocatedAmount']),
                      style: const TextStyle(fontSize: 12),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),
            TextButton.icon(
              onPressed: () => setState(() => _extractedData = null),
              icon: const Icon(Icons.edit, size: 16),
              label: const Text('Edit Prompt'),
            ),
          ],
        ),
      ),
    );
  }
}
