// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BKM6BLKc2NojsO27ccvZx0uJZUSCbfs',
    appId: '1:331195204285:web:bbaa8e513c6a1d95f42dd4',
    messagingSenderId: '331195204285',
    projectId: 'outstanding-management-app',
    authDomain: 'outstanding-management-app.firebaseapp.com',
    storageBucket: 'outstanding-management-app.firebasestorage.app',
    measurementId: 'G-WMKJZ0PRYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ2EtQKAeNBLkuNUXmVgW_N475mrWHPiM',
    appId: '1:331195204285:android:1fc78f424be04584f42dd4',
    messagingSenderId: '331195204285',
    projectId: 'outstanding-management-app',
    storageBucket: 'outstanding-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNBU7SyqKPywPAG7Ki32tBdwI57Y9ID8',
    appId: '1:331195204285:ios:457f0ffb416055e3f42dd4',
    messagingSenderId: '331195204285',
    projectId: 'outstanding-management-app',
    storageBucket: 'outstanding-management-app.firebasestorage.app',
    iosBundleId: 'com.example.outstandingManagementApp',
  );
}
