import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../providers/invoice_provider.dart';
import '../../providers/party_provider.dart';
import '../../providers/auth_provider.dart';
import '../../models/invoice_model.dart';
import '../../models/party_model.dart';

class AddInvoiceScreen extends ConsumerStatefulWidget {
  final String invoiceType;

  const AddInvoiceScreen({super.key, required this.invoiceType});

  @override
  ConsumerState<AddInvoiceScreen> createState() => _AddInvoiceScreenState();
}

class _AddInvoiceScreenState extends ConsumerState<AddInvoiceScreen> {
  final _formKey = GlobalKey<FormState>();
  
  // Invoice Details
  String _invoiceNumber = ''; // Will generate on backend ideally, or local logic
  DateTime _invoiceDate = DateTime.now();
  DateTime? _dueDate;
  
  // Party Selection
  Party? _selectedParty;
  
  // Items
  final List<InvoiceItemConfig> _items = [InvoiceItemConfig()];
  
  // Calculations
  bool _isPercentageDiscount = false;
  final _discountController = TextEditingController(text: '0');
  final _taxController = TextEditingController(text: '0');
  final _notesController = TextEditingController();

  bool _isLoading = false;
  final currencyFormat = NumberFormat.currency(locale: 'en_IN', symbol: '₹');

  @override
  void initState() {
    super.initState();
    _invoiceNumber = '${widget.invoiceType == 'sales' ? 'INV' : 'BILL'}-${DateTime.now().millisecondsSinceEpoch.toString().substring(7)}';
    
    _discountController.addListener(_updateTotals);
    _taxController.addListener(_updateTotals);
  }

  @override
  void dispose() {
    _discountController.dispose();
    _taxController.dispose();
    _notesController.dispose();
    for (var item in _items) {
      item.dispose();
    }
    super.dispose();
  }

  void _updateTotals() {
    setState(() {}); // Rebuild to run getters
  }

  double get subtotal {
    return _items.fold(0, (sum, item) => sum + item.amount);
  }

  double get discountAmount {
    double val = double.tryParse(_discountController.text) ?? 0;
    if (_isPercentageDiscount) {
      return subtotal * (val / 100);
    }
    return val;
  }

  double get taxAmount {
    double taxable = subtotal - discountAmount;
    double taxPercentage = double.tryParse(_taxController.text) ?? 0;
    return taxable * (taxPercentage / 100);
  }

  double get totalAmount {
    return (subtotal - discountAmount) + taxAmount;
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedParty == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a party')));
      return;
    }
    
    // Ensure all items are calculated
    for (var item in _items) {
      item.calculate();
    }

    if (totalAmount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Total amount must be greater than 0')));
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = ref.read(authStateProvider).value;
      if (user == null) throw Exception("Not authenticated");

      final items = _items.map((conf) => InvoiceItem(
        description: conf.descController.text,
        quantity: double.tryParse(conf.qtyController.text) ?? 1,
        rate: double.tryParse(conf.rateController.text) ?? 0,
        amount: conf.amount,
      )).toList();

      final invoice = Invoice(
        id: '', // Generated by repo
        userId: user.uid,
        partyId: _selectedParty!.id,
        partyName: _selectedParty!.name,
        invoiceType: widget.invoiceType,
        invoiceNumber: _invoiceNumber,
        invoiceDate: _invoiceDate,
        dueDate: _dueDate,
        subtotal: subtotal,
        discountType: _isPercentageDiscount ? 'percentage' : 'fixed',
        discountValue: double.tryParse(_discountController.text) ?? 0,
        discountAmount: discountAmount,
        taxPercentage: double.tryParse(_taxController.text) ?? 0,
        taxAmount: taxAmount,
        totalAmount: totalAmount,
        outstandingAmount: totalAmount,
        paymentStatus: 'unpaid',
        notes: _notesController.text,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await ref.read(invoiceRepositoryProvider).createInvoice(invoice, items);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Invoice created successfully')),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // Determine party type to fetch based on invoice type
    final partyType = widget.invoiceType == 'sales' ? 'customer' : 'supplier';
    final partiesAsync = ref.watch(partiesProvider(partyType));

    return Scaffold(
      appBar: AppBar(
        title: Text('New ${widget.invoiceType == 'sales' ? 'Sales' : 'Purchase'} Invoice'),
        actions: [
          IconButton(
            icon: const Icon(Icons.check),
            onPressed: (_isLoading || partiesAsync.isLoading) ? null : _save,
          )
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // 1. Party Selection
                  partiesAsync.when(
                    data: (parties) {
                      return DropdownButtonFormField<Party>(
                        decoration: InputDecoration(
                          labelText: 'Select ${widget.invoiceType == 'sales' ? 'Customer' : 'Supplier'} *',
                          prefixIcon: const Icon(Icons.person),
                        ),
                        value: _selectedParty,
                        items: parties.map((p) => DropdownMenuItem(value: p, child: Text(p.name))).toList(),
                        onChanged: (val) => setState(() => _selectedParty = val),
                        validator: (v) => v == null ? 'Please select a party' : null,
                      );
                    },
                    loading: () => const CircularProgressIndicator(),
                    error: (e,s) => Text('Error loading parties: $e'),
                  ),
                  const SizedBox(height: 16),

                  // 2. Dates & Numbers
                  Row(
                    children: [
                      Expanded(
                        child: InkWell(
                          onTap: () async {
                            final date = await showDatePicker(
                              context: context,
                              initialDate: _invoiceDate,
                              firstDate: DateTime(2000),
                              lastDate: DateTime(2100),
                            );
                            if (date != null) setState(() => _invoiceDate = date);
                          },
                          child: InputDecorator(
                            decoration: const InputDecoration(labelText: 'Invoice Date', prefixIcon: Icon(Icons.calendar_today, size: 18)),
                            child: Text(DateFormat('dd MMM yyyy').format(_invoiceDate)),
                          ),
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: InkWell(
                          onTap: () async {
                            final date = await showDatePicker(
                              context: context,
                              initialDate: _dueDate ?? _invoiceDate.add(const Duration(days: 15)),
                              firstDate: _invoiceDate,
                              lastDate: DateTime(2100),
                            );
                            if (date != null) setState(() => _dueDate = date);
                          },
                          child: InputDecorator(
                            decoration: const InputDecoration(labelText: 'Due Date', prefixIcon: Icon(Icons.event, size: 18)),
                            child: Text(_dueDate != null ? DateFormat('dd MMM yyyy').format(_dueDate!) : 'Not Set'),
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // 3. Line Items
                  Text('Line Items', style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  
                  ListView.builder(
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    itemCount: _items.length,
                    itemBuilder: (context, index) {
                      final item = _items[index];
                      return Card(
                        margin: const EdgeInsets.only(bottom: 12),
                        child: Padding(
                          padding: const EdgeInsets.all(12.0),
                          child: Column(
                            children: [
                              Row(
                                children: [
                                  Expanded(
                                    child: TextFormField(
                                      controller: item.descController,
                                      decoration: const InputDecoration(labelText: 'Description', filled: false),
                                      validator: (v) => v == null || v.isEmpty ? 'Required' : null,
                                    ),
                                  ),
                                  if (_items.length > 1) 
                                    IconButton(
                                      icon: const Icon(Icons.delete, color: Colors.red),
                                      onPressed: () => setState(() => _items.removeAt(index)),
                                    )
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                children: [
                                  Expanded(
                                    flex: 1,
                                    child: TextFormField(
                                      controller: item.qtyController,
                                      keyboardType: TextInputType.number,
                                      decoration: const InputDecoration(labelText: 'Qty', filled: false),
                                      onChanged: (_) => _updateTotals(),
                                    ),
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    flex: 2,
                                    child: TextFormField(
                                      controller: item.rateController,
                                      keyboardType: TextInputType.number,
                                      decoration: const InputDecoration(labelText: 'Rate', filled: false),
                                      onChanged: (_) => _updateTotals(),
                                    ),
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    flex: 2,
                                    child: Container(
                                      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
                                      alignment: Alignment.centerRight,
                                      decoration: BoxDecoration(
                                        color: Colors.grey.shade100,
                                        borderRadius: BorderRadius.circular(4),
                                      ),
                                      child: Text(
                                        currencyFormat.format(item.amount),
                                        style: const TextStyle(fontWeight: FontWeight.bold),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
                  
                  TextButton.icon(
                    onPressed: () => setState(() => _items.add(InvoiceItemConfig())),
                    icon: const Icon(Icons.add),
                    label: const Text('Add Item'),
                  ),
                  const Divider(height: 32),

                  // 4. Calculations Row
                  Row(
                    children: [
                       Expanded(
                         child: TextFormField(
                            controller: _discountController,
                            keyboardType: TextInputType.number,
                            decoration: InputDecoration(
                              labelText: 'Discount',
                              suffixIcon: IconButton(
                                icon: Icon(_isPercentageDiscount ? Icons.percent : Icons.currency_rupee),
                                onPressed: () {
                                  setState(() => _isPercentageDiscount = !_isPercentageDiscount);
                                  _updateTotals();
                                },
                              )
                            ),
                         ),
                       ),
                       const SizedBox(width: 16),
                       Expanded(
                         child: TextFormField(
                            controller: _taxController,
                            keyboardType: TextInputType.number,
                            decoration: const InputDecoration(
                              labelText: 'Tax %',
                              suffixIcon: Icon(Icons.percent),
                            ),
                         ),
                       ),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // 5. Final Summary Box
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.primary.withOpacity(0.05),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Theme.of(context).colorScheme.primary.withOpacity(0.2)),
                    ),
                    child: Column(
                      children: [
                        _buildSummaryRow('Subtotal', subtotal),
                        if (discountAmount > 0)
                          _buildSummaryRow('Discount', -discountAmount),
                        if (taxAmount > 0)
                          _buildSummaryRow('Tax', taxAmount),
                        const Divider(height: 24),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            const Text('Total Amount', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                            Text(
                              currencyFormat.format(totalAmount),
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 22, color: Theme.of(context).colorScheme.primary),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 24),
                  TextFormField(
                    controller: _notesController,
                    maxLines: 2,
                    decoration: const InputDecoration(labelText: 'Notes / Remarks'),
                  ),
                  const SizedBox(height: 48),
                ],
              ),
            ),
    );
  }

  Widget _buildSummaryRow(String label, double amount) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(color: Colors.grey)),
          Text(currencyFormat.format(amount)),
        ],
      ),
    );
  }
}

// UI State holder for line items
class InvoiceItemConfig {
  final descController = TextEditingController();
  final qtyController = TextEditingController(text: '1');
  final rateController = TextEditingController(text: '0');

  double get amount {
    final qty = double.tryParse(qtyController.text) ?? 0;
    final rate = double.tryParse(rateController.text) ?? 0;
    return qty * rate;
  }

  void calculate() {} // just triggers getter

  void dispose() {
    descController.dispose();
    qtyController.dispose();
    rateController.dispose();
  }
}
