name: Flutter CI

on:
  push:
    branches: [ "main", "enhancements" ]
  pull_request:
    branches: [ "main", "enhancements" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Create Dummy .env File
        run: |
          echo "FIREBASE_ANDROID_API_KEY=dummy_key" > .env
          echo "FIREBASE_IOS_API_KEY=dummy_key" >> .env
          echo "FIREBASE_WEB_API_KEY=dummy_key" >> .env
        
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze project source
        run: flutter analyze
