name: Play Store Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Still allow manual trigger if needed

jobs:
  build:
    name: Build AAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create key.properties
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create Production .env file
        run: |
          echo "FIREBASE_ANDROID_API_KEY=${{ secrets.ANDROID_KEY }}" > .env
          echo "FIREBASE_IOS_API_KEY=${{ secrets.IOS_KEY }}" >> .env
          echo "FIREBASE_WEB_API_KEY=${{ secrets.WEB_KEY }}" >> .env

      - name: Build App Bundle & APK
        run: |
          flutter build appbundle --release
          flutter build apk --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
